cwd: './'

tpl:
    dep: "'./{{comp}}/{{dep}}'"

contentTpl:
    tpl: '<div class="o-{{comp}}">{{EOL}}</div>'
    scss: '.o-{{comp}} {{{EOL}}}'
    js: "define('comp/{{comp}}/index', [{{deps}}], function ({{depsVars}}) {{{EOL}}})"

baseDeps: []

varRegx :
    baseDep: [ ".+\/([^\/]+)'$" , '$$$1']
    tpl: [ "([^\.]+).+$" , "$$$1Tpl"]

extension:
    tpl: 'html'

defaultName:
    js: 'index'
    scss: 'base'
    tpl: 'main'
